In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r"C:\Users\sk062\Documents\Data\Google Search\Search.csv")
Data = pd.DataFrame(df)
Data["Data"] = pd.to_datetime(Data["Data"])

In [4]:
Data.head()

        Data  AIR JORDAN  AIR FORCE  AIR MAX  DUNK
0 2019-12-15          43         22       62     6
1 2019-12-22          47         22       65     4
2 2019-12-29          51         26      100     3
3 2020-01-05          44         20       74     4
4 2020-01-12          41         23       68     4

In [13]:
list(Data["Data"].unique())

[Timestamp('2019-12-15 00:00:00'),
 Timestamp('2019-12-22 00:00:00'),
 Timestamp('2019-12-29 00:00:00'),
 Timestamp('2020-01-05 00:00:00'),
 Timestamp('2020-01-12 00:00:00'),
 Timestamp('2020-01-19 00:00:00'),
 Timestamp('2020-01-26 00:00:00'),
 Timestamp('2020-02-02 00:00:00'),
 Timestamp('2020-02-09 00:00:00'),
 Timestamp('2020-02-16 00:00:00'),
 Timestamp('2020-02-23 00:00:00'),
 Timestamp('2020-03-01 00:00:00'),
 Timestamp('2020-03-08 00:00:00'),
 Timestamp('2020-03-15 00:00:00'),
 Timestamp('2020-03-22 00:00:00'),
 Timestamp('2020-03-29 00:00:00'),
 Timestamp('2020-04-05 00:00:00'),
 Timestamp('2020-04-12 00:00:00'),
 Timestamp('2020-04-19 00:00:00'),
 Timestamp('2020-04-26 00:00:00'),
 Timestamp('2020-05-03 00:00:00'),
 Timestamp('2020-05-10 00:00:00'),
 Timestamp('2020-05-17 00:00:00'),
 Timestamp('2020-05-24 00:00:00'),
 Timestamp('2020-05-31 00:00:00'),
 Timestamp('2020-06-07 00:00:00'),
 Timestamp('2020-06-14 00:00:00'),
 Timestamp('2020-06-21 00:00:00'),
 Timestamp('2020-06-28 00:00:00'),
 Timestamp('2020-07-05 00:00:00'),
 Timestamp('2020-07-12 00:00:00'),
 Timestamp('2020-07-19 00:00:00'),
 Timestamp('2020-07-26 00:00:00'),
 Timestamp('2020-08-02 00:00:00'),
 Timestamp('2020-08-09 00:00:00'),
 Timestamp('2020-08-16 00:00:00'),
 Timestamp('2020-08-23 00:00:00'),
 Timestamp('2020-08-30 00:00:00'),
 Timestamp('2020-09-06 00:00:00'),
 Timestamp('2020-09-13 00:00:00'),
 Timestamp('2020-09-20 00:00:00'),
 Timestamp('2020-09-27 00:00:00'),
 Timestamp('2020-10-04 00:00:00'),
 Timestamp('2020-10-11 00:00:00'),
 Timestamp('2020-10-18 00:00:00'),
 Timestamp('2020-10-25 00:00:00'),
 Timestamp('2020-11-01 00:00:00'),
 Timestamp('2020-11-08 00:00:00'),
 Timestamp('2020-11-15 00:00:00'),
 Timestamp('2020-11-22 00:00:00'),
 Timestamp('2020-11-29 00:00:00'),
 Timestamp('2020-12-06 00:00:00'),
 Timestamp('2020-12-13 00:00:00'),
 Timestamp('2020-12-20 00:00:00'),
 Timestamp('2020-12-27 00:00:00'),
 Timestamp('2021-01-03 00:00:00'),
 Timestamp('2021-01-10 00:00:00'),
 Timestamp('2021-01-17 00:00:00'),
 Timestamp('2021-01-24 00:00:00'),
 Timestamp('2021-01-31 00:00:00'),
 Timestamp('2021-02-07 00:00:00'),
 Timestamp('2021-02-14 00:00:00'),
 Timestamp('2021-02-21 00:00:00'),
 Timestamp('2021-02-28 00:00:00'),
 Timestamp('2021-03-07 00:00:00'),
 Timestamp('2021-03-14 00:00:00'),
 Timestamp('2021-03-21 00:00:00'),
 Timestamp('2021-03-28 00:00:00'),
 Timestamp('2021-04-04 00:00:00'),
 Timestamp('2021-04-11 00:00:00'),
 Timestamp('2021-04-18 00:00:00'),
 Timestamp('2021-04-25 00:00:00'),
 Timestamp('2021-05-02 00:00:00'),
 Timestamp('2021-05-09 00:00:00'),
 Timestamp('2021-05-16 00:00:00'),
 Timestamp('2021-05-23 00:00:00'),
 Timestamp('2021-05-30 00:00:00'),
 Timestamp('2021-06-06 00:00:00'),
 Timestamp('2021-06-13 00:00:00'),
 Timestamp('2021-06-20 00:00:00'),
 Timestamp('2021-06-27 00:00:00'),
 Timestamp('2021-07-04 00:00:00'),
 Timestamp('2021-07-11 00:00:00'),
 Timestamp('2021-07-18 00:00:00'),
 Timestamp('2021-07-25 00:00:00'),
 Timestamp('2021-08-01 00:00:00'),
 Timestamp('2021-08-08 00:00:00'),
 Timestamp('2021-08-15 00:00:00'),
 Timestamp('2021-08-22 00:00:00'),
 Timestamp('2021-08-29 00:00:00'),
 Timestamp('2021-09-05 00:00:00'),
 Timestamp('2021-09-12 00:00:00'),
 Timestamp('2021-09-19 00:00:00'),
 Timestamp('2021-09-26 00:00:00'),
 Timestamp('2021-10-03 00:00:00'),
 Timestamp('2021-10-10 00:00:00'),
 Timestamp('2021-10-17 00:00:00'),
 Timestamp('2021-10-24 00:00:00'),
 Timestamp('2021-10-31 00:00:00'),
 Timestamp('2021-11-07 00:00:00'),
 Timestamp('2021-11-14 00:00:00'),
 Timestamp('2021-11-21 00:00:00'),
 Timestamp('2021-11-28 00:00:00'),
 Timestamp('2021-12-05 00:00:00'),
 Timestamp('2021-12-12 00:00:00'),
 Timestamp('2021-12-19 00:00:00'),
 Timestamp('2021-12-26 00:00:00'),
 Timestamp('2022-01-02 00:00:00'),
 Timestamp('2022-01-09 00:00:00'),
 Timestamp('2022-01-16 00:00:00'),
 Timestamp('2022-01-23 00:00:00'),
 Timestamp('2022-01-30 00:00:00'),
 Timestamp('2022-02-06 00:00:00'),
 Timestamp('2022-02-13 00:00:00'),
 Timestamp('2022-02-20 00:00:00'),
 Timestamp('2022-02-27 00:00:00'),
 Timestamp('2022-03-06 00:00:00'),
 Timestamp('2022-03-13 00:00:00'),
 Timestamp('2022-03-20 00:00:00'),
 Timestamp('2022-03-27 00:00:00'),
 Timestamp('2022-04-03 00:00:00'),
 Timestamp('2022-04-10 00:00:00'),
 Timestamp('2022-04-17 00:00:00'),
 Timestamp('2022-04-24 00:00:00'),
 Timestamp('2022-05-01 00:00:00'),
 Timestamp('2022-05-08 00:00:00'),
 Timestamp('2022-05-15 00:00:00'),
 Timestamp('2022-05-22 00:00:00'),
 Timestamp('2022-05-29 00:00:00'),
 Timestamp('2022-06-05 00:00:00'),
 Timestamp('2022-06-12 00:00:00'),
 Timestamp('2022-06-19 00:00:00'),
 Timestamp('2022-06-26 00:00:00'),
 Timestamp('2022-07-03 00:00:00'),
 Timestamp('2022-07-10 00:00:00'),
 Timestamp('2022-07-17 00:00:00'),
 Timestamp('2022-07-24 00:00:00'),
 Timestamp('2022-07-31 00:00:00'),
 Timestamp('2022-08-07 00:00:00'),
 Timestamp('2022-08-14 00:00:00'),
 Timestamp('2022-08-21 00:00:00'),
 Timestamp('2022-08-28 00:00:00'),
 Timestamp('2022-09-04 00:00:00'),
 Timestamp('2022-09-11 00:00:00'),
 Timestamp('2022-09-18 00:00:00'),
 Timestamp('2022-09-25 00:00:00'),
 Timestamp('2022-10-02 00:00:00'),
 Timestamp('2022-10-09 00:00:00'),
 Timestamp('2022-10-16 00:00:00'),
 Timestamp('2022-10-23 00:00:00'),
 Timestamp('2022-10-30 00:00:00'),
 Timestamp('2022-11-06 00:00:00'),
 Timestamp('2022-11-13 00:00:00'),
 Timestamp('2022-11-20 00:00:00'),
 Timestamp('2022-11-27 00:00:00'),
 Timestamp('2022-12-04 00:00:00'),
 Timestamp('2022-12-11 00:00:00'),
 Timestamp('2022-12-18 00:00:00'),
 Timestamp('2022-12-25 00:00:00'),
 Timestamp('2023-01-01 00:00:00'),
 Timestamp('2023-01-08 00:00:00'),
 Timestamp('2023-01-15 00:00:00'),
 Timestamp('2023-01-22 00:00:00'),
 Timestamp('2023-01-29 00:00:00'),
 Timestamp('2023-02-05 00:00:00'),
 Timestamp('2023-02-12 00:00:00'),
 Timestamp('2023-02-19 00:00:00'),
 Timestamp('2023-02-26 00:00:00'),
 Timestamp('2023-03-05 00:00:00'),
 Timestamp('2023-03-12 00:00:00'),
 Timestamp('2023-03-19 00:00:00'),
 Timestamp('2023-03-26 00:00:00'),
 Timestamp('2023-04-02 00:00:00'),
 Timestamp('2023-04-09 00:00:00'),
 Timestamp('2023-04-16 00:00:00'),
 Timestamp('2023-04-23 00:00:00'),
 Timestamp('2023-04-30 00:00:00'),
 Timestamp('2023-05-07 00:00:00'),
 Timestamp('2023-05-14 00:00:00'),
 Timestamp('2023-05-21 00:00:00'),
 Timestamp('2023-05-28 00:00:00'),
 Timestamp('2023-06-04 00:00:00'),
 Timestamp('2023-06-11 00:00:00'),
 Timestamp('2023-06-18 00:00:00'),
 Timestamp('2023-06-25 00:00:00'),
 Timestamp('2023-07-02 00:00:00'),
 Timestamp('2023-07-09 00:00:00'),
 Timestamp('2023-07-16 00:00:00'),
 Timestamp('2023-07-23 00:00:00'),
 Timestamp('2023-07-30 00:00:00'),
 Timestamp('2023-08-06 00:00:00'),
 Timestamp('2023-08-13 00:00:00'),
 Timestamp('2023-08-20 00:00:00'),
 Timestamp('2023-08-27 00:00:00'),
 Timestamp('2023-09-03 00:00:00'),
 Timestamp('2023-09-10 00:00:00'),
 Timestamp('2023-09-17 00:00:00'),
 Timestamp('2023-09-24 00:00:00'),
 Timestamp('2023-10-01 00:00:00'),
 Timestamp('2023-10-08 00:00:00'),
 Timestamp('2023-10-15 00:00:00'),
 Timestamp('2023-10-22 00:00:00'),
 Timestamp('2023-10-29 00:00:00'),
 Timestamp('2023-11-05 00:00:00'),
 Timestamp('2023-11-12 00:00:00'),
 Timestamp('2023-11-19 00:00:00'),
 Timestamp('2023-11-26 00:00:00'),
 Timestamp('2023-12-03 00:00:00'),
 Timestamp('2023-12-10 00:00:00'),
 Timestamp('2023-12-17 00:00:00'),
 Timestamp('2023-12-24 00:00:00'),
 Timestamp('2023-12-31 00:00:00'),
 Timestamp('2024-01-07 00:00:00'),
 Timestamp('2024-01-14 00:00:00'),
 Timestamp('2024-01-21 00:00:00'),
 Timestamp('2024-01-28 00:00:00'),
 Timestamp('2024-02-04 00:00:00'),
 Timestamp('2024-02-11 00:00:00'),
 Timestamp('2024-02-18 00:00:00'),
 Timestamp('2024-02-25 00:00:00'),
 Timestamp('2024-03-03 00:00:00'),
 Timestamp('2024-03-10 00:00:00'),
 Timestamp('2024-03-17 00:00:00'),
 Timestamp('2024-03-24 00:00:00'),
 Timestamp('2024-03-31 00:00:00'),
 Timestamp('2024-04-07 00:00:00'),
 Timestamp('2024-04-14 00:00:00'),
 Timestamp('2024-04-21 00:00:00'),
 Timestamp('2024-04-28 00:00:00'),
 Timestamp('2024-05-05 00:00:00'),
 Timestamp('2024-05-12 00:00:00'),
 Timestamp('2024-05-19 00:00:00'),
 Timestamp('2024-05-26 00:00:00'),
 Timestamp('2024-06-02 00:00:00'),
 Timestamp('2024-06-09 00:00:00'),
 Timestamp('2024-06-16 00:00:00'),
 Timestamp('2024-06-23 00:00:00'),
 Timestamp('2024-06-30 00:00:00'),
 Timestamp('2024-07-07 00:00:00'),
 Timestamp('2024-07-14 00:00:00'),
 Timestamp('2024-07-21 00:00:00'),
 Timestamp('2024-07-28 00:00:00'),
 Timestamp('2024-08-04 00:00:00'),
 Timestamp('2024-08-11 00:00:00'),
 Timestamp('2024-08-18 00:00:00'),
 Timestamp('2024-08-25 00:00:00'),
 Timestamp('2024-09-01 00:00:00'),
 Timestamp('2024-09-08 00:00:00'),
 Timestamp('2024-09-15 00:00:00'),
 Timestamp('2024-09-22 00:00:00'),
 Timestamp('2024-09-29 00:00:00'),
 Timestamp('2024-10-06 00:00:00'),
 Timestamp('2024-10-13 00:00:00'),
 Timestamp('2024-10-20 00:00:00'),
 Timestamp('2024-10-27 00:00:00'),
 Timestamp('2024-11-03 00:00:00'),
 Timestamp('2024-11-10 00:00:00'),
 Timestamp('2024-11-17 00:00:00'),
 Timestamp('2024-11-24 00:00:00'),
 Timestamp('2024-12-01 00:00:00'),
 Timestamp('2024-12-08 00:00:00'),
 Timestamp('2024-12-15 00:00:00')]

In [14]:
Data_2019 = Data[(Data['Data'] >= '2019-12-15') & (Data['Data'] <= '2019-12-29')]
Data_2020 = Data[(Data['Data'] >= '2020-01-05') & (Data['Data'] <= '2020-12-27')]
Data_2021 = Data[(Data['Data'] >= '2021-01-03') & (Data['Data'] <= '2021-12-26')]
Data_2022 = Data[(Data['Data'] >= '2022-01-02') & (Data['Data'] <= '2022-12-25')]
Data_2023 = Data[(Data['Data'] >= '2023-01-01') & (Data['Data'] <= '2023-12-31')]
Data_2024 = Data[(Data['Data'] >= '2024-01-07') & (Data['Data'] <= '2024-12-15')]

In [16]:
print(Data_2019.shape)
print(Data_2020.shape)
print(Data_2021.shape)
print(Data_2022.shape)
print(Data_2023.shape)
print(Data_2024.shape)

(3, 5)
(52, 5)
(52, 5)
(52, 5)
(53, 5)
(50, 5)

In [18]:
# H0 = 帰無仮説（H₀）: 2019年と2020年の「AIR_MAX」の検索数の平均に差はない。
# H1 = 対立仮説（H₁）: 2019年と2020年の「AIR_MAX」の検索数の平均に差がある。

In [19]:
import scipy.stats as stats

In [ ]:


# 2019年と2020年の検索数データ（例）
search_2019_AIR_JORDAN = Data_2019["AIR_JORDAN"] 
search_2020_AIR_JORDAN = Data_2

# 対応のないt検定
t_stat, p_value = stats.ttest_ind(search_2019, search_2020)

# 結果を表示
print("t値:", t_stat)
print("p値:", p_value)

# 有意水準α=0.05で判定
if p_value < 0.05:
    print("帰無仮説を棄却します。2019年と2020年の平均に有意差があります。")
else:
    print("帰無仮説を採択します。2019年と2020年の平均に有意差はありません。")